// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABsejpvDfK6RTKrwOydpMu1iYyBqMSvtk',
    appId: '1:978633956922:web:d2e26293f4aa1bbbb15f03',
    messagingSenderId: '978633956922',
    projectId: 'e-commerce-1-55069',
    authDomain: 'e-commerce-1-55069.firebaseapp.com',
    storageBucket: 'e-commerce-1-55069.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJa2EBX5_tsV1YfalMNUzvxWCY565h0rI',
    appId: '1:978633956922:android:ec683b12c173d8d0b15f03',
    messagingSenderId: '978633956922',
    projectId: 'e-commerce-1-55069',
    storageBucket: 'e-commerce-1-55069.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBujzlvkAbmWrmIsddwTv6pmR11j4cXEo0',
    appId: '1:978633956922:ios:bda1f3e596d946f5b15f03',
    messagingSenderId: '978633956922',
    projectId: 'e-commerce-1-55069',
    storageBucket: 'e-commerce-1-55069.appspot.com',
    iosClientId: '978633956922-n7309a0chr87mndnini0pntckg3q6116.apps.googleusercontent.com',
    iosBundleId: 'com.example.flowerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBujzlvkAbmWrmIsddwTv6pmR11j4cXEo0',
    appId: '1:978633956922:ios:bda1f3e596d946f5b15f03',
    messagingSenderId: '978633956922',
    projectId: 'e-commerce-1-55069',
    storageBucket: 'e-commerce-1-55069.appspot.com',
    iosClientId: '978633956922-n7309a0chr87mndnini0pntckg3q6116.apps.googleusercontent.com',
    iosBundleId: 'com.example.flowerApp',
  );
}
